### ISSUE TITLE
有赞的客服系统是否使用了swoole？

### ISSUE THREAD

**Issue by konukk** [zanphp/zan#13]

**Comment by konukk** [comment]
之前关注过有赞，你们好像用的tornado是吧

**Comment by agalwood** [comment]
木有，已经从tornado转向Java了

**Comment by konukk** [comment]
在你们内部，zan是怎么定位的呢？

**Comment by agalwood** [comment]
定位和我们开源的版本定位是一样的：

> 提供最简单的方式开发面向C10K+的高并发HTTP服务或SOA服务

**Comment by zxcvdavid** [comment]
@kinkk 有兴趣了解更多，可以加QQ群：115728122

**Comment by ice6** [comment]
@agalwood 内部已经转java了，😄
php社区一个劲的跟java，真不如直接转java省事儿
