### ISSUE TITLE
windows下php7环境安装后执行zan报错

### ISSUE THREAD

**Issue by LamentOfTheHighborne** [zanphp/zan#15]
php-7.0.10-Win32-VC14-x64

E:\Program Files>composer -disable-tls global require youzan/zan-installer
Changed current directory to C:/Users/Wind/AppData/Roaming/Composer
You are running Composer with SSL/TLS protection disabled.
Warning: Accessing packagist.org over http which is an insecure protocol.
Using version ^1.0 for youzan/zan-installer
./composer.json has been updated
Loading composer repositories with package information
Warning: Accessing packagist.org over http which is an insecure protocol.
Updating dependencies (including require-dev)
- Installing seld/cli-prompt (1.0.2)
  Failed to download seld/cli-prompt from dist: You must enable the openssl extension to download files via https
  Now trying to download from source
- Installing seld/cli-prompt (1.0.2)
  Cloning 8cbe10923cae5bcd7c5a713f6703fc4727c8c1b4
- Installing league/climate (3.2.1)
  Failed to download league/climate from dist: You must enable the openssl extension to download files via https
  Now trying to download from source
- Installing league/climate (3.2.1)
  Cloning b103fc8faa3780c802cc507d5f0ff534ecc94fb5
- Installing youzan/zan-installer (1.0.9)
  Failed to download youzan/zan-installer from dist: You must enable the openssl extension to download files via https
  Now trying to download from source
- Installing youzan/zan-installer (1.0.9)
  Cloning fcd45ec79b84843052a00401dad4570f69e5f993

Writing lock file
Generating autoload files

E:\Program Files>zan

---

  /\ \  /\ \
  \ `\`\/'/ ___   __  __  ____      __      ___
   `\`\ /' / **`\/\ \/\ \/\_ ,`\  /'**`\  /' _`\
     `\ \ \/\ \L\ \ \ _\ \/_/  /_/\ \L._/\ \/\ \
       \ _\ _**_/\ _**_/ /____\ __/._\ _\ _\
        \/_/\/___/  \/**_/  \/_**_/\/__/\/_/\/_/\/_/
Create a new ZanPhp application.
Which type application would you create? (use <space> to select)
PHP Fatal error:  Method League\CLImate\TerminalObject\Dynamic\Checkbox\Checkbox::__toString() must not throw an exception, caught Error: Call to undefined function League\CLImate\TerminalObject\Helper\mb_strwidth() in C:\Users\Wind\AppData\Roaming\Composer\vendor\league\climate\src\TerminalObject\Dynamic\Checkbox\CheckboxGroup.php on line 0

Fatal error: Method League\CLImate\TerminalObject\Dynamic\Checkbox\Checkbox::__toString() must not throw an exception, caught Error: Call to undefined function League\CLImate\TerminalObject\Helper\mb_strwidth() in C:\Users\Wind\AppData\Roaming\Composer\vendor\league\climate\src\TerminalObject\Dynamic\Checkbox\CheckboxGroup.php on line 0

E:\Program Files>

**Comment by winglechen** [comment]
windows下没测试过，应该兼容性有点问题的

**Comment by agalwood** [comment]
`mb_strwidth` 需要PHP安装mbstring扩展
http://php.net/manual/zh/mbstring.installation.php

**Comment by LamentOfTheHighborne** [comment]
多谢，打开mbstring和ssl之后，又报下面的错。算了，win10下着实搞不定，放弃了。还是转战Linux吧。
![image](https://cloud.githubusercontent.com/assets/10486840/18249669/4430bd38-73b2-11e6-987d-b686db120621.png)
