### ISSUE TITLE
Server start时没有写入pid文件，bin/server reload等无效

### ISSUE THREAD

**Issue by farlee** [zanphp/zan#28]
Network/Server/ServerBase.php 中writePid 被 return了：

    protected function writePid($pid)
    {
        return;

        $pidFilePath = $this->getPidFilePath();
        if (false === file_put_contents($pidFilePath, $pid)) {
            sys_error("write pid into $pidFilePath failed");
        }
    }

**Comment by zxcvdavid** [comment]
我们目前是使用supervisor来进行管理的，接下去会增加命令行管理的模式，谢谢反馈 :)
