### ISSUE TITLE
Enable sockets support, require sockets extension

### ISSUE THREAD

**Issue by jockchou** [zanphp/zan#29]
vagrant@homestead:/usr/local/src/zan/zan-extension$ sudo make
/bin/bash /usr/local/src/zan/zan-extension/libtool --mode=compile cc  -I. -I/usr/local/src/zan/zan-extension -DPHP_ATOM_INC -I/usr/local/src/zan/zan-extension/include -I/usr/local/src/zan/zan-extension/main -I/usr/local/src/zan/zan-extension -I/usr/include/php/20160303 -I/usr/include/php/20160303/main -I/usr/include/php/20160303/TSRM -I/usr/include/php/20160303/Zend -I/usr/include/php/20160303/ext -I/usr/include/php/20160303/ext/date/lib -I/usr/local/src/zan/zan-extension/include  -DHAVE_CONFIG_H  -std=gnu99 -Wall -pthread -g -O2 -fstack-check -fbounds-check -fstack-protector -fstack-protector-all -fno-strict-aliasing   -c /usr/local/src/zan/zan-extension/swoole.c -o swoole.lo 
libtool: compile:  cc -I. -I/usr/local/src/zan/zan-extension -DPHP_ATOM_INC -I/usr/local/src/zan/zan-extension/include -I/usr/local/src/zan/zan-extension/main -I/usr/local/src/zan/zan-extension -I/usr/include/php/20160303 -I/usr/include/php/20160303/main -I/usr/include/php/20160303/TSRM -I/usr/include/php/20160303/Zend -I/usr/include/php/20160303/ext -I/usr/include/php/20160303/ext/date/lib -I/usr/local/src/zan/zan-extension/include -DHAVE_CONFIG_H -std=gnu99 -Wall -pthread -g -O2 -fstack-check -fbounds-check -fstack-protector -fstack-protector-all -fno-strict-aliasing -c /usr/local/src/zan/zan-extension/swoole.c  -fPIC -DPIC -o .libs/swoole.o
In file included from /usr/local/src/zan/zan-extension/swoole.c:20:0:
/usr/local/src/zan/zan-extension/php_swoole.h:140:2: error: #error "Enable sockets support, require sockets extension."
 #error "Enable sockets support, require sockets extension."
  ^
Makefile:194: recipe for target 'swoole.lo' failed
make: *** [swoole.lo] Error 1

**Comment by xhjcehust** [comment]
需要安装php官方sockets扩展的，具体见https://github.com/youzan/zan  README.md
