### ISSUE TITLE
youzan/zanhttp的Demo正常启动 ,访问无输出

### ISSUE THREAD

**Issue by unixcx** [zanphp/zan#3]
现象: 
下载Demo后,服务正常启动.
curl http://127.0.0.1:8030 无输出

检查:
server端 控制台 提示错误为:
`PHP Parse error:  syntax error, unexpected '*', expecting ',' or ';' in /var/www/html/zanhttp/vendor/zanphp/zan/src/Network/Http/RequestHandler.php on line 43
[2016-06-21 11:21:26 $27845.0]  WARNING swManager_check_exit_status: worker#1 abnormal exit, status=255, signal=0
http worker error .....
http worker start .....`

原因: 
/src/Network/Http/RequestHandler.php on line 43
`const DEFAULT_TIMEOUT = 30 * 1000;`  // const 不支持表达式赋值 修改为
`const DEFAULT_TIMEOUT = 30000;` 即可

**Comment by winglechen** [comment]
感谢反馈，你的php版本是什么呢？我们主要的测试场景是php5.6以上版本, 也建议php的版本为5.6， php7我们在测试中

**Comment by winglechen** [comment]
不好意思，误把issue关掉了
