### ISSUE TITLE
我怎么才能把nova替换成标准thrift或者带有线程池的http调用

### ISSUE THREAD

**Issue by gouchaoer** [zanphp/zan#30]
由于微服务可能用c++用go用java写，而且有的已经写成了thrift的，有的已经写成了http server的，现在我希望把nova-thrift替换成标准thrift怎么操作呢？另外我在zanphp里访问http server的话可以用tcp连接池么？

**Comment by gouchaoer** [comment]
由于我们业务量不大，不在乎thrift的那点压缩比，用thrift修改了一点接口之后2边都得改，所以还是倾向http server的rest调用方式。。。但是这个调用优缺点就是http建立连接要tcp握手消耗，而且tcp连接断了之后发送端口一点时间内不可用，qps大了就可能导致端口不够用了，如果可以用tcp线程池就好了（也就是keep-alive的http，这条tcp连接在多次请求中复用）。。。另外http server端我还是想用etcd自动注册，如果能基于redis做服务发现那更简单更好，我怎么改造呢？

**Comment by gouchaoer** [comment]
我看到这里有tcp连接池，还有一个httpclient，如果能用httpclient包装这个连接池就好了。。。

**Comment by jockchou** [comment]
http是基于请求响应的无状态协议，是短连接，用完就断开了，哪来的连接池一说？

**Comment by xhjcehust** [comment]
框架自定义序列化协议和RPC调用方式不久就会推出，敬请期待哦
