### ISSUE TITLE
连续coredump

### ISSUE THREAD

**Issue by yunnian** [zanphp/zan#38]
启动时 若配了redis连接池 连续coredump

[2017-07-16 01:51:26 #0] worker *0 starting .....
php(32850,0x7fff94a633c0) malloc: *** error for object 0x7fd3c8301030: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug

**Comment by zxcvdavid** [comment]
请发一下你的redis连接池配置 (resource/config/$ENV/connection/redis.php)
如果可以，请按 https://bugs.php.net/bugs-generating-backtrace.php 打印一下core的堆栈信息发出来

**Comment by zxcvdavid** [comment]
@yunnian 已经Fixed 请更新zan的版本重新编译 谢谢
