### ISSUE TITLE
swoole 2.0会自带协程的实现，zan框架是否会跟进？

### ISSUE THREAD

**Issue by kcloze** [zanphp/zan#5]
这样就不用写yield了

**Comment by winglechen** [comment]
我们和swoole2.0走的方向不太一样
swoole2.0走的方向是要干掉golang; 
我们的方向是搭建一个php+golang的技术生态；
选择哪个方向？大家可以根据自己的场景来决定

**Comment by winglechen** [comment]
http://tech.youzan.com/zan-swoole2/  这个是我们的一些想法
