### ISSUE TITLE
bash  ./zan报错

### ISSUE THREAD

**Issue by aogg** [zanphp/zan#6]
![image](https://cloud.githubusercontent.com/assets/8998031/17511281/cffcf8c2-5e54-11e6-8905-a0b22a169cb5.png)

直接运行报错，目前已定位到是tput命令不存在的问题，如何解决？
如果要安装tput如何安装？

系统为docker的ubuntu:14.04

**Comment by agalwood** [comment]
这有点奇怪啊～

> tput is part of the ncurses package and is supplied with most Linux distributions.
> http://linuxcommand.org/lc3_adv_tput.php#availability

**Comment by aogg** [comment]
@agalwood   要不兼容下tput不存在这种模式，目前你们用来干嘛了？

**Comment by ghost** [comment]
@aogg 你安装了ncurses包么?安装一下试试呢
