### ISSUE TITLE
memory_limit写死在这里不太好吧?

### ISSUE THREAD

**Issue by ghost** [zanphp/zan#7]
https://github.com/youzan/zan/blob/master/src/Foundation/Booting/InitializeEnv.php#L18

是否应该增加一个配置选项? 或者遵循php.ini的设置呢?

**Comment by ghost** [comment]
同样还有写死的
https://github.com/youzan/zan/blob/master/src/Foundation/Booting/LoadConfiguration.php#L18

```

        date_default_timezone_set('Asia/Shanghai');
        mb_internal_encoding('UTF-8');
```

如果是要处理其他时区.或者其他编码类型. 

建议是不是遵循php.ini的设置,或者抽离出一个config选项?

**Comment by winglechen** [comment]
可以的，哈哈，我们有点懒

**Comment by winglechen** [comment]
谢谢反馈
