### ISSUE TITLE
默认的错误页面是不是可以不依赖有赞的静态资源

### ISSUE THREAD

**Issue by ghost** [zanphp/zan#9]
https://github.com/youzan/zan/blob/master/src/Network/Http/Exception/Handler/BizErrorHandler.php
https://github.com/youzan/zan/blob/master/src/Network/Http/Exception/Handler/InternalErrorHandler.php

这些文件里面都有html字符串,发现都调用了有赞的静态资源

```

    <link rel="icon" href="https://su.yzcdn.cn/v2/image/yz_fc.ico" />
.....
<script src="https://su.yzcdn.cn/jquery-2.0.3.min.js"></script>
<script src="https://su.yzcdn.cn/jquery.parallaxify-0.0.2.min.js"></script>
```

如果用的人多,就相当于对你们cdn或者web服务器的ddos, 会消耗你们的资源

**Comment by winglechen** [comment]
可以，我们把错误页改可成配置的
